### ISSUE TITLE
nxp cp command not working when copying one prefix to other prefix in the same bucket. 

### ISSUE THREAD

**Issue by mourya92** [generalui/s3p#11]
Hello, 

`npx s3p cp --bucket my-bucket --prefix oldpath/ --to-bucket my-bucket --to-prefix newpath/`

Getting error : 

> InvalidRequest: This copy request is illegal because it is trying to copy an object to itself without changing the object's metadata, storage class, website redirect location or encryption attributes.
>           at Request.extractError (/Users/ssmourya/Downloads/node_modules/aws-sdk/lib/services/s3.js:700:35)
>           at Request.callListeners (/Users/ssmourya/Downloads/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
>           at Request.emit (/Users/ssmourya/Downloads/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
>           at Request.emit (/Users/ssmourya/Downloads/node_modules/aws-sdk/lib/request.js:688:14)
>           at Request.transition (/Users/ssmourya/Downloads/node_modules/aws-sdk/lib/request.js:22:10)
>           at AcceptorStateMachine.runTo (/Users/ssmourya/Downloads/node_modules/aws-sdk/lib/state_machine.js:14:12)
>           at /Users/ssmourya/Downloads/node_modules/aws-sdk/lib/state_machine.js:26:10
>           at Request.<anonymous> (/Users/ssmourya/Downloads/node_modules/aws-sdk/lib/request.js:38:9)
>           at Request.<anonymous> (/Users/ssmourya/Downloads/node_modules/aws-sdk/lib/request.js:690:12)
>           at Request.callListeners (/Users/ssmourya/Downloads/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
>           at Request.emit (/Users/ssmourya/Downloads/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
>           at Request.emit (/Users/ssmourya/Downloads/node_modules/aws-sdk/lib/request.js:688:14)
>           at Request.transition (/Users/ssmourya/Downloads/node_modules/aws-sdk/lib/request.js:22:10)
>           at AcceptorStateMachine.runTo (/Users/ssmourya/Downloads/node_modules/aws-sdk/lib/state_machine.js:14:12)
>           at /Users/ssmourya/Downloads/node_modules/aws-sdk/lib/state_machine.js:26:10
>           at Request.<anonymous> (/Users/ssmourya/Downloads/node_modules/aws-sdk/lib/request.js:38:9)
>           at Request.<anonymous> (/Users/ssmourya/Downloads/node_modules/aws-sdk/lib/request.js:690:12)
>           at Request.callListeners (/Users/ssmourya/Downloads/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
>           at callNextListener (/Users/ssmourya/Downloads/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
>           at IncomingMessage.onEnd (/Users/ssmourya/Downloads/node_modules/aws-sdk/lib/event_listeners.js:313:13)
>           at IncomingMessage.emit (events.js:203:15)
>           at IncomingMessage.EventEmitter.emit (domain.js:448:20)

Is this supported at all ? 

When I used different bucket names, command works as expected. 

Also, I tried to pass --storage-class=STANDARD option just to introduce a 'change'. s3p wouldn't even process that option. 

Can you please give a example command ?

**Comment by siebrand** [comment]
I've recently used this, and it works. Can you still reproduce this?

**Comment by siebrand** [comment]
On `storage-class`: As far as I can tell, this is simply not supported at the moment. All writes are `S3 Standard`. I created an feature request for this (#21).

Please try to not report multiple issues in a single report.

**Comment by shanebdavis** [comment]
It sounds like an object was copied literally from and to the exact same key. I think S3P should handle this relatively well. It should just skip over that one copy and continue to copy the rest. You could possibly use "sync" to avoid this error.
