### ISSUE TITLE
No more updates every second after error

### ISSUE THREAD

**Issue by siebrand** [generalui/s3p#14]
I'm trying to synchronize two buckets. While doing this, I see this error occur. And when that happens, I no longer see updates from s3p appear every second in the output. The "aws s3 rm" commands *are* still output. I'm expecting status output like this (lines broken for readability):

```
s3p: d: 3m 43s, items: 1000245, items/s: 4481, listRequests: 1348, listWorkers: throttled,
  listQueue: 68, copied 17297/79588 47.31gB/117.22gB 217.01mB/s inFlight: 575.42mB copyWorkers: 500 + 0
  copyQueue: 61810 + 0 same: 920651(1.73tB) toDelete: 28325(77.75gB)
```

I'm using a recent and clean Amazon Linux 2 AMI on a c6g.2xlarge instance. 16GB RAM, 8 CPU, 20GB EBS disk. Access to the buckets is given through an instance role. The source bucket is in another account.

Commands executed to get to this point:

``` 
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.0/install.sh | bash
nvm install 15.2.0
# @todo There is a command that probably needs to go here to make "npm" work.
npm install -g npm@7.0.10
npm install install s3p
# Apparently need this, because one run ran out of memory (default 512MB?)
export NODE_OPTIONS="--max-old-space-size=8192"
time npx s3p sync --bucket source_bucket --to-bucket target_bucket >> output.txt 2>&1
```

Example error:

```eachRecursive:
  startAfter:      :A-QS/[..]/[..]/[..].jpg
  stopAt:          :B
  usePrefixBisect: false
  error:
    Error:
      class: class Error
      stack:
        NoSuchKey: The specified key does not exist.
            at Request.extractError (/home/ec2-user/node_modules/aws-sdk/lib/services/s3.js:700:35)
            at Request.callListeners (/home/ec2-user/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
            at Request.emit (/home/ec2-user/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
            at Request.emit (/home/ec2-user/node_modules/aws-sdk/lib/request.js:688:14)
            at Request.transition (/home/ec2-user/node_modules/aws-sdk/lib/request.js:22:10)
            at AcceptorStateMachine.runTo (/home/ec2-user/node_modules/aws-sdk/lib/state_machine.js:14:12)
            at /home/ec2-user/node_modules/aws-sdk/lib/state_machine.js:26:10
            at Request.<anonymous> (/home/ec2-user/node_modules/aws-sdk/lib/request.js:38:9)
            at Request.<anonymous> (/home/ec2-user/node_modules/aws-sdk/lib/request.js:690:12)
            at Request.callListeners (/home/ec2-user/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
            at Request.emit (/home/ec2-user/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
            at Request.emit (/home/ec2-user/node_modules/aws-sdk/lib/request.js:688:14)
            at Request.transition (/home/ec2-user/node_modules/aws-sdk/lib/request.js:22:10)
            at AcceptorStateMachine.runTo (/home/ec2-user/node_modules/aws-sdk/lib/state_machine.js:14:12)
            at /home/ec2-user/node_modules/aws-sdk/lib/state_machine.js:26:10
            at Request.<anonymous> (/home/ec2-user/node_modules/aws-sdk/lib/request.js:38:9)
            at Request.<anonymous> (/home/ec2-user/node_modules/aws-sdk/lib/request.js:690:12)
            at Request.callListeners (/home/ec2-user/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
            at callNextListener (/home/ec2-user/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
            at IncomingMessage.onEnd (/home/ec2-user/node_modules/aws-sdk/lib/event_listeners.js:313:13)
            at IncomingMessage.emit (node:events:341:22)
            at IncomingMessage.EventEmitter.emit (node:domain:467:12)
```

The object that's mentioned for "startAfter" actually does exist in the source bucket as well as the target bucket. Both objects haven't been touched recently (object date of 2018).

**Comment by jalbstmeijer** [comment]
Seem to hit the same issue. Also running a Amazon Linux 2 AMI. In my case with regular iam env credentials.

**Comment by shanebdavis** [comment]
Interesting bug. I'm guessing it has to do with some specific keys that are tripping the algorithm up. 

It looks like you may have keys like `A-QS/[..]/[..]/[..].jpg` ? If you can share publicly, can you post some of the actual keys you have with square brackets in them?

**Comment by siebrand** [comment]
Here is a small sample of actual keys. The 4 character prefix consists of the first 4 characters of an "Asset ID" (see below), which is the second "directory" level. A third level contains "*_renditions/" or "asset/" in which the actual objects are located.

```
0-Si/0-Si8_c5aPTAJkkUaAe70f/1_renditions/maxWidth_1600_maxHeight_1600_page_0.jpg
0-Si/0-Si8_c5aPTAJkkUaAe70f/1_renditions/thumbnail.jpg
0-Si/0-Si8_c5aPTAJkkUaAe70f/asset/2.indd
0-Si/0-SiYoLQ4fZB4YeoV-aeEX/1_renditions/maxWidth_1600_maxHeight_1600.jpg
0-Si/0-SiYoLQ4fZB4YeoV-aeEX/1_renditions/thumbnail.jpg
0-Si/0-SiYoLQ4fZB4YeoV-aeEX/2_renditions/maxWidth_1600_maxHeight_1600.jpg
0-Si/0-SiYoLQ4fZB4YeoV-aeEX/2_renditions/thumbnail.jpg
0-Si/0-SiYoLQ4fZB4YeoV-aeEX/3_renditions/maxWidth_1600_maxHeight_1600.jpg
0-Si/0-SiYoLQ4fZB4YeoV-aeEX/3_renditions/thumbnail.jpg
0-Si/0-SiYoLQ4fZB4YeoV-aeEX/asset/1.jpg
0-Si/0-SiYoLQ4fZB4YeoV-aeEX/asset/4.jpg
0-Si/0-SiYoLQ4fZB4YeoV-aeEX/asset/7.jpg
```

Asset IDs start with a hex character (0-9, A-H), followed by 21 characters out of A-Z, a-z, 0-9, underscore and dash.

**Comment by siebrand** [comment]
The lack of updates every second is also mentioned at https://github.com/generalui/s3p/issues/26#issuecomment-800174513

**Comment by shanebdavis** [comment]
Thanks for sharing the file names. They look totally fine.

There have been a few bug fixes which might be related to this. Let me know if you still see issues.

**Comment by siebrand** [comment]
Hasn’t been observed in a while, also because this runs mostly fully automated.
