### ISSUE TITLE
sync something's not right

### ISSUE THREAD

**Issue by jalbstmeijer** [generalui/s3p#15]
Running s3p 2.10.1 with node v14.15.1.

Getting this error on a sync between two s3 buckets.
I do not see anything special in 100xx/noxx/20xx/ that might explain the error.

eachRecursive:
  startAfter: :100xx/noxx/20xx/1/21/08036xx.txt
  stopAt:
    :100xx/noxx/20xx/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  usePrefixBisect: true
  error:
    Error:
      class: class Error
      stack:
        Error: Whoops! 100xx/noxx/20xx/1/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <= 100xx/noxx/20xx/1/~ <= 100xx/noxx/20xx/10/xx/085180xx.txt -- something's not right
            at /root/node_modules/s3p/source/S3Parallel/Lib/S3Keys.js:108:27
            at getBisectKey (/root/node_modules/s3p/source/S3Parallel/Lib/S3Keys.js:113:21)
            at eachRecursive (/root/node_modules/s3p/source/S3Parallel/S3Comprehensions.js:631:27)
            at Function.each (/root/node_modules/s3p/source/S3Parallel/S3Comprehensions.js:886:20)
            at Function._compareList (/root/node_modules/s3p/source/S3Parallel/S3Comprehensions.js:943:25)
            at /root/node_modules/s3p/source/S3Parallel/S3Comprehensions.js:727:28
            at r (/root/node_modules/bluebird/js/browser/bluebird.core.min.js:31:18764)
            at o._settlePromiseFromHandler (/root/node_modules/bluebird/js/browser/bluebird.core.min.js:31:6959)
            at o._settlePromise (/root/node_modules/bluebird/js/browser/bluebird.core.min.js:31:7762)
            at o._settlePromise0 (/root/node_modules/bluebird/js/browser/bluebird.core.min.js:31:8463)
            at o._settlePromises (/root/node_modules/bluebird/js/browser/bluebird.core.min.js:31:9818)
            at o._fulfill (/root/node_modules/bluebird/js/browser/bluebird.core.min.js:31:8834)
            at o._resolveCallback (/root/node_modules/bluebird/js/browser/bluebird.core.min.js:31:5695)
            at o._settlePromiseFromHandler (/root/node_modules/bluebird/js/browser/bluebird.core.min.js:31:7114)
            at o._settlePromise (/root/node_modules/bluebird/js/browser/bluebird.core.min.js:31:7762)
            at o._settlePromise0 (/root/node_modules/bluebird/js/browser/bluebird.core.min.js:31:8463)
            at o._settlePromises (/root/node_modules/bluebird/js/browser/bluebird.core.min.js:31:9818)
            at o._fulfill (/root/node_modules/bluebird/js/browser/bluebird.core.min.js:31:8834)
            at o._resolveCallback (/root/node_modules/bluebird/js/browser/bluebird.core.min.js:31:5695)
            at o._settlePromiseFromHandler (/root/node_modules/bluebird/js/browser/bluebird.core.min.js:31:7114)
            at o._settlePromise (/root/node_modules/bluebird/js/browser/bluebird.core.min.js:31:7762)
            at o._settlePromise0 (/root/node_modules/bluebird/js/browser/bluebird.core.min.js:31:8463)

**Comment by abrantes01** [comment]
Hello @jalbstmeijer , did you find any solution ? Facing the same issue with the sync options

**Comment by jalbstmeijer** [comment]
> Hello @jalbstmeijer , did you find any solution ? Facing the same issue with the sync options

No, unfortunately. The error gives me no clue what could be wrong to debug any further.
Was hoping on feedback of the developer.

**Comment by niallfleming** [comment]
Me too. I ended up choosing a start-after further down the tree to sync much of the bucket and then relied on awscli to catch the rest. I have around 3 million files, with around .8 million under one key, it could be that it's not clever enough to split that key down?

**Comment by jalbstmeijer** [comment]
Hi @niallfleming , thanks for sharing your workaround.

I played around with start-after and stop-at options and found out s3p barfs on only 2 objects from my 800k objects 600GB bucket.

By excluding these two objects with start-after and stop-at I'm able to complete the sync.
Could not find anything special about these objects to explain why s3p has issues with them.

If the developer wants any additional information on these objects or other attributes of the bucket, I'm happy to provide them.

Gr, J

**Comment by shanebdavis** [comment]
Hey guys. Sorry for the very slow reply. Github has issues around notifications and issues.

Anyway, can you give me examples of item keys that cause problems?

**Comment by jalbstmeijer** [comment]
Hi shanebdavis,

See my initial error report. There where no special characters mentioned in the file names in the error output. So I just replaced general character with "x" to anonymize it.
If you have a better way of identifying the problematic object, please let me know and I will try to catch it.

Gr, J

**Comment by niallfleming** [comment]
@shanebdavis here's the error I receive. If I start the sync after this point it succeeds (--start-after cdn/pluginfile.php/102769). Interestingly I can sync --prefix cdn/pluginfile.php/1 on its own ok 

Key:    cdn/pluginfile.php/1/totara_customfield/course_filemgr/1007282/jmc_publish_MOTOTRBO_System_Planner/lxp-html-olh-format-en-us-1/26c7ad28.html

Unhandled rejection Error: Whoops! cdn/pluginfile.php/1/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <= cdn/pluginfile.php/1/~ <= cdn/pluginfile.php/102769/mod_scorm/content/3/ref/ref29707.htm -- something's not right
    at /root/.npm/_npx/301b345c5affbb3b/node_modules/s3p/source/S3Parallel/Lib/S3Keys.js:108:27
    at getBisectKey (/root/.npm/_npx/301b345c5affbb3b/node_modules/s3p/source/S3Parallel/Lib/S3Keys.js:113:21)
    at eachRecursive (/root/.npm/_npx/301b345c5affbb3b/node_modules/s3p/source/S3Parallel/S3Comprehensions.js:631:27)
    at Function.each (/root/.npm/_npx/301b345c5affbb3b/node_modules/s3p/source/S3Parallel/S3Comprehensions.js:886:20)
    at Function._compareList (/root/.npm/_npx/301b345c5affbb3b/node_modules/s3p/source/S3Parallel/S3Comprehensions.js:943:25)
    at /root/.npm/_npx/301b345c5affbb3b/node_modules/s3p/source/S3Parallel/S3Comprehensions.js:727:28
    at r (/root/.npm/_npx/301b345c5affbb3b/node_modules/bluebird/js/browser/bluebird.core.min.js:31:18764)
    at o._settlePromiseFromHandler (/root/.npm/_npx/301b345c5affbb3b/node_modules/bluebird/js/browser/bluebird.core.min.js:31:6959)
    at o._settlePromise (/root/.npm/_npx/301b345c5affbb3b/node_modules/bluebird/js/browser/bluebird.core.min.js:31:7762)
    at o._settlePromise0 (/root/.npm/_npx/301b345c5affbb3b/node_modules/bluebird/js/browser/bluebird.core.min.js:31:8463)
    at o._settlePromises (/root/.npm/_npx/301b345c5affbb3b/node_modules/bluebird/js/browser/bluebird.core.min.js:31:9818)
    at o._fulfill (/root/.npm/_npx/301b345c5affbb3b/node_modules/bluebird/js/browser/bluebird.core.min.js:31:8834)
    at o._resolveCallback (/root/.npm/_npx/301b345c5affbb3b/node_modules/bluebird/js/browser/bluebird.core.min.js:31:5695)
    at o._settlePromiseFromHandler (/root/.npm/_npx/301b345c5affbb3b/node_modules/bluebird/js/browser/bluebird.core.min.js:31:7114)
    at o._settlePromise (/root/.npm/_npx/301b345c5affbb3b/node_modules/bluebird/js/browser/bluebird.core.min.js:31:7762)
    at o._settlePromise0 (/root/.npm/_npx/301b345c5affbb3b/node_modules/bluebird/js/browser/bluebird.core.min.js:31:8463)
    at o._settlePromises (/root/.npm/_npx/301b345c5affbb3b/node_modules/bluebird/js/browser/bluebird.core.min.js:31:9818)
    at o._fulfill (/root/.npm/_npx/301b345c5affbb3b/node_modules/bluebird/js/browser/bluebird.core.min.js:31:8834)
    at o._resolveCallback (/root/.npm/_npx/301b345c5affbb3b/node_modules/bluebird/js/browser/bluebird.core.min.js:31:5695)
    at o._settlePromiseFromHandler (/root/.npm/_npx/301b345c5affbb3b/node_modules/bluebird/js/browser/bluebird.core.min.js:31:7114)
    at o._settlePromise (/root/.npm/_npx/301b345c5affbb3b/node_modules/bluebird/js/browser/bluebird.core.min.js:31:7762)
    at o._settlePromise0 (/root/.npm/_npx/301b345c5affbb3b/node_modules/bluebird/js/browser/bluebird.core.min.js:31:8463)

**Comment by shanebdavis** [comment]
@niallfleming Thanks! I'll take a look.

**Comment by memo-devel** [comment]
@shanebdavis Any update on this? I ran into the same issue, using s3p 3.4.1 and node 16.0.0.

**Comment by shanebdavis** [comment]
Could you try again? I've patched at least one error similar to this since 3.4.1.
