### ISSUE TITLE
sync returning strange "you must do this" messages and aws-cli command failing with "invalid argument type

### ISSUE THREAD

**Issue by thatandyrose** [generalui/s3p#17]
When I ran `sync` I got a load of messages like this:

`aws s3 rm s3://somekey # you must do this`

Also every now and then errors like this:

```
 Error: Command failed: aws s3 cp 's3://sourcebucket/key.mp4' 's3://destinationbucket/key.mp4'

        usage: aws s3 cp <LocalPath> <S3Uri> or <S3Uri> <LocalPath> or <S3Uri> <S3Uri>
        Error: Invalid argument type

            at ChildProcess.exithandler (child_process.js:295:12)
            at ChildProcess.emit (events.js:210:5)
            at ChildProcess.EventEmitter.emit (domain.js:476:20)
            at maybeClose (internal/child_process.js:1021:16)
            at Socket.<anonymous> (internal/child_process.js:430:11)
            at Socket.emit (events.js:210:5)
            at Socket.EventEmitter.emit (domain.js:476:20)
            at Pipe.<anonymous> (net.js:658:12)
```

Using windows Powershell FYI.

Thanks so much for this tool!

**Comment by siebrand** [comment]
These are actually two reports.

On `you must do this`: You really should. `s3p` does not delete objects for you in the target bucket when you sync. You could read this as "Execute this awscli command to delete objects absent in target bucket and present in source bucket". I'd recommend you submit a patch to improve the output and/or documentation if you're able to.

On the `aws s3 cp` error: Does this happen every time for the same object? If so, can you be more specific about the full object name? s3p has limitations on which characters are supported in object names.

**Comment by jurampark-pala** [comment]
@siebrand Thanks for your answer, one question I have for `you must do this`. If there're "objects absent in target bucket and present in source bucket", shouldn't it be copied instead of asking user to delete?

**Comment by siebrand** [comment]
> @siebrand [..]If there're "objects absent in target bucket and present in source bucket", shouldn't it be copied instead of asking user to delete?

Yes. I will correct my initial reply on this issue.

**Comment by jurampark-pala** [comment]
> > @siebrand [..]If there're "objects absent in target bucket and present in source bucket", shouldn't it be copied instead of asking user to delete?
> 
> Yes. I will correct my initial reply on this issue.

Thanks for your quick reply! It cleared up my confusion!
