### ISSUE TITLE
prefix, startAfter, and stopAt

### ISSUE THREAD

**Issue by eml** [generalui/s3p#5]
hello! I'm trying to get a listing of a bucket for which I only have access under a specific prefix. I'm running this:

```
s3p ls --bucket mybucket --prefix myprefix/
```

s3p is giving me an 'Access Denied' error. However, the aws command line tool works fine:

```
aws s3 ls s3://mybucket/myprefix/
```

The error message s3p is giving me is below. 

Am I doing something wrong? My [utterly naive] guess, based on the error, is that you're converting the prefix into a filter, and S3 doesn't like that.

```
S3.list-error:
  bucket:     :mybucket
  prefix:     undefined
  startAfter: :myprefix/
  limit:      1000
  error:
    Error:
      class: class Error
      stack:
        AccessDenied: Access Denied
            at Request.extractError (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/services/s3.js:837:35)
            at Request.callListeners (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
            at Request.emit (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
            at Request.emit (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:688:14)
            at Request.transition (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:22:10)
            at AcceptorStateMachine.runTo (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/state_machine.js:14:12)
            at /Users/eml/tmp/s3p/node_modules/aws-sdk/lib/state_machine.js:26:10
            at Request.<anonymous> (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:38:9)
            at Request.<anonymous> (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:690:12)
            at Request.callListeners (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
            at Request.emit (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
            at Request.emit (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:688:14)
            at Request.transition (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:22:10)
            at AcceptorStateMachine.runTo (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/state_machine.js:14:12)
            at /Users/eml/tmp/s3p/node_modules/aws-sdk/lib/state_machine.js:26:10
            at Request.<anonymous> (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:38:9)
            at Request.<anonymous> (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:690:12)
            at Request.callListeners (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
            at callNextListener (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
            at IncomingMessage.onEnd (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/event_listeners.js:313:13)
            at IncomingMessage.emit (events.js:215:7)
            at IncomingMessage.EventEmitter.emit (domain.js:476:20)

eachRecursive:
  startAfter: :myprefix/
  stopAt:
    :myprefix/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  usePrefixBisect: false
  error:
    Error:
      class: class Error
      stack:
        AccessDenied: Access Denied
            at Request.extractError (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/services/s3.js:837:35)
            at Request.callListeners (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
            at Request.emit (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
            at Request.emit (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:688:14)
            at Request.transition (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:22:10)
            at AcceptorStateMachine.runTo (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/state_machine.js:14:12)
            at /Users/eml/tmp/s3p/node_modules/aws-sdk/lib/state_machine.js:26:10
            at Request.<anonymous> (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:38:9)
            at Request.<anonymous> (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:690:12)
            at Request.callListeners (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
            at Request.emit (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
            at Request.emit (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:688:14)
            at Request.transition (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:22:10)
            at AcceptorStateMachine.runTo (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/state_machine.js:14:12)
            at /Users/eml/tmp/s3p/node_modules/aws-sdk/lib/state_machine.js:26:10
            at Request.<anonymous> (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:38:9)
            at Request.<anonymous> (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:690:12)
            at Request.callListeners (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
            at callNextListener (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
            at IncomingMessage.onEnd (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/event_listeners.js:313:13)
            at IncomingMessage.emit (events.js:215:7)
            at IncomingMessage.EventEmitter.emit (domain.js:476:20)

S3.list-error:
  bucket:     :myprefix
  prefix:     undefined
  startAfter: :myprefix/O
  limit:      1000
  error:
    Error:
      class: class Error
      stack:
        AccessDenied: Access Denied
            at Request.extractError (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/services/s3.js:837:35)
            at Request.callListeners (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
            at Request.emit (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
            at Request.emit (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:688:14)
            at Request.transition (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:22:10)
            at AcceptorStateMachine.runTo (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/state_machine.js:14:12)
            at /Users/eml/tmp/s3p/node_modules/aws-sdk/lib/state_machine.js:26:10
            at Request.<anonymous> (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:38:9)
            at Request.<anonymous> (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:690:12)
            at Request.callListeners (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
            at Request.emit (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
            at Request.emit (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:688:14)
            at Request.transition (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:22:10)
            at AcceptorStateMachine.runTo (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/state_machine.js:14:12)
            at /Users/eml/tmp/s3p/node_modules/aws-sdk/lib/state_machine.js:26:10
            at Request.<anonymous> (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:38:9)
            at Request.<anonymous> (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:690:12)
            at Request.callListeners (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
            at callNextListener (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
            at IncomingMessage.onEnd (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/event_listeners.js:313:13)
            at IncomingMessage.emit (events.js:215:7)
            at IncomingMessage.EventEmitter.emit (domain.js:476:20)

Unhandled rejection AccessDenied: Access Denied
    at Request.extractError (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/services/s3.js:837:35)
    at Request.callListeners (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/eml/tmp/s3p/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/eml/tmp/s3p/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/Users/eml/tmp/s3p/node_modules/aws-sdk/lib/event_listeners.js:313:13)
    at IncomingMessage.emit (events.js:215:7)
    at IncomingMessage.EventEmitter.emit (domain.js:476:20)

```

**Comment by eml** [comment]
(couple edits up there, as I manually changed the name of the bucket/prefix to protect the innocent!)

**Comment by roguepullrequest** [comment]
Similar issue. Something is up

**Comment by eml** [comment]
Just a follow-up to say, you guys are friggin' awesome for sharing this project. This tool has saved me soo many hours of time.

**Comment by thejessleigh** [comment]
Not sure if you've solved this issue, but in case anyone else stumbles on this -

s3p uses amazon's s3 sdk, which checks for aws access and secret key environment variables wherever you're running. If you have awscli or something similar configured with profiles in `~/.aws/config` it does not check these by default. Check to make sure your environment variables are set when you run. Also make sure that whatever entity you're using creds for has permissions to the bucket.

If you're doing anything like syncing across accounts, you may have to check that the source account has full access to the bucket in the destination account.

**Comment by shanebdavis** [comment]
Thankyou @thejessleigh. I expect that's exactly it. Generally I like to set up access to a specific account (e.g. ACME) on ~/.aws/credentials and then `SET AWS_PROFILE=ACME` in environment S3P will run in.

**Comment by shanebdavis** [comment]
@eml can you confirm this solves the problem?

**Comment by russellkt** [comment]
I have a project where I have to backup a bunch of files from s3 and was so excited to see this project.  However, I'm getting the same error as original poster and have confirmed the aws s3 cli works fine.  I've exported AWS_DEFAULT_REGION, AWS_ACCESS_KEY_ID, and AWS_SECRET_ACCESS_KEY but keep getting the same "Access Denied" error.  On this particular bucket I don't have access to any methods at the top level but have access after the prefix.  Based on the output it appears that the prefix gets translated to startAfter.  Does that matter?  Any other thoughts?

works
```aws s3 ls s3://client/data/```

does not work
```npx s3p ls --bucket client --prefix data/```

throws

```S3.list-error:
  bucket:     :client
  prefix:     undefined
  startAfter: :data/O
  limit:      1000
  error:      Error:
    class: class Error
    stack:
      AccessDenied: Access Denied
          at Request.extractError (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/services/s3.js:714:35)
          at Request.callListeners (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
          at Request.emit (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
          at Request.emit (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/request.js:688:14)
          at Request.transition (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/request.js:22:10)
          at AcceptorStateMachine.runTo (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/state_machine.js:14:12)
          at /Users/user/git/s3p-try/node_modules/aws-sdk/lib/state_machine.js:26:10
          at Request.<anonymous> (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/request.js:38:9)
          at Request.<anonymous> (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/request.js:690:12)
          at Request.callListeners (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
          at Request.emit (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
          at Request.emit (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/request.js:688:14)
          at Request.transition (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/request.js:22:10)
          at AcceptorStateMachine.runTo (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/state_machine.js:14:12)
          at /Users/user/git/s3p-try/node_modules/aws-sdk/lib/state_machine.js:26:10
          at Request.<anonymous> (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/request.js:38:9)
          at Request.<anonymous> (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/request.js:690:12)
          at Request.callListeners (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
          at callNextListener (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
          at IncomingMessage.onEnd (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/event_listeners.js:336:13)
          at IncomingMessage.emit (node:events:406:35)
          at IncomingMessage.emit (node:domain:475:12)

eachRecursive:
  startAfter: :data/
  stopAt:
    :data/~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  usePrefixBisect: false
  error:           Error:
    class: class Error
    stack:
      AccessDenied: Access Denied
          at Request.extractError (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/services/s3.js:714:35)
          at Request.callListeners (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
          at Request.emit (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
          at Request.emit (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/request.js:688:14)
          at Request.transition (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/request.js:22:10)
          at AcceptorStateMachine.runTo (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/state_machine.js:14:12)
          at /Users/user/git/s3p-try/node_modules/aws-sdk/lib/state_machine.js:26:10
          at Request.<anonymous> (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/request.js:38:9)
          at Request.<anonymous> (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/request.js:690:12)
          at Request.callListeners (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
          at Request.emit (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
          at Request.emit (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/request.js:688:14)
          at Request.transition (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/request.js:22:10)
          at AcceptorStateMachine.runTo (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/state_machine.js:14:12)
          at /Users/user/git/s3p-try/node_modules/aws-sdk/lib/state_machine.js:26:10
          at Request.<anonymous> (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/request.js:38:9)
          at Request.<anonymous> (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/request.js:690:12)
          at Request.callListeners (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
          at callNextListener (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
          at IncomingMessage.onEnd (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/event_listeners.js:336:13)
          at IncomingMessage.emit (node:events:406:35)
          at IncomingMessage.emit (node:domain:475:12)

Error:
  class: class Error
  stack:
    AccessDenied: Access Denied
        at Request.extractError (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/services/s3.js:714:35)
        at Request.callListeners (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
        at Request.emit (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
        at Request.emit (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/request.js:688:14)
        at Request.transition (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/request.js:22:10)
        at AcceptorStateMachine.runTo (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/state_machine.js:14:12)
        at /Users/user/git/s3p-try/node_modules/aws-sdk/lib/state_machine.js:26:10
        at Request.<anonymous> (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/request.js:38:9)
        at Request.<anonymous> (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/request.js:690:12)
        at Request.callListeners (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
        at Request.emit (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
        at Request.emit (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/request.js:688:14)
        at Request.transition (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/request.js:22:10)
        at AcceptorStateMachine.runTo (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/state_machine.js:14:12)
        at /Users/user/git/s3p-try/node_modules/aws-sdk/lib/state_machine.js:26:10
        at Request.<anonymous> (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/request.js:38:9)
        at Request.<anonymous> (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/request.js:690:12)
        at Request.callListeners (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
        at callNextListener (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
        at IncomingMessage.onEnd (/Users/user/git/s3p-try/node_modules/aws-sdk/lib/event_listeners.js:336:13)
        at IncomingMessage.emit (node:events:406:35)
        at IncomingMessage.emit (node:domain:475:12)
```

I'm using aws-sdk v3

**Comment by klimchuk** [comment]
Script was working for me on EC2 instance 2 days ago but now it's saying
Error:
  class: class Error
  stack:
    AccessDenied: Access Denied

aws s3 ls s3://mybucket works fine

**Comment by klimchuk** [comment]
Funny thing happened to me yesterday: I've misspelled name of bucket and got Access Denied

**Comment by zekena2** [comment]
Any update on this? I'm seeing the same problem when using it inside kubernetes using the env variable AWS_WEB_IDENTITY_TOKEN_FILE.
