### ISSUE TITLE
NoSuchKey error for key that exists

### ISSUE THREAD

**Issue by stephenwiebe** [generalui/s3p#53]
s3p sync runs for a little bit, and then it keeps getting the error `NoSuchKey: The specified key does not exist.` on one of a couple specific keys. I've confirmed that this object exists in the source bucket, and it exists in the destination bucket now too. There's nothing particularly weird about this object that I can determine (it does have a space in the name). I thought maybe if I synced this particular folder with `aws s3 sync` that I could get past the error, but unfortunately it's still erroring out. `aws s3 sync` worked to sync the folder without errors. The IAM role I'm using has full S3 permissions. The buckets are cross-region but same-account.

Error:

```
eachRecursive:
  startAfter: "accounts/0032c61e-38b1-4604-ba0b-51573bd1cfc7/assets/wcp0ZaXeT3WF9rST5YhY_Drawing Mock up V8 with Side 3.jpg"
  stopAt:          :accounts/?
  usePrefixBisect: false
  error:           Error:
    class: class Error
    stack:
      NoSuchKey: The specified key does not exist.
          at Request.extractError (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/services/s3.js:714:35)
          at Request.callListeners (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
          at Request.emit (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
          at Request.emit (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/request.js:688:14)
          at Request.transition (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/request.js:22:10)
          at AcceptorStateMachine.runTo (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/state_machine.js:14:12)
          at /home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/state_machine.js:26:10
          at Request.<anonymous> (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/request.js:38:9)
          at Request.<anonymous> (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/request.js:690:12)
          at Request.callListeners (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
          at Request.emit (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
          at Request.emit (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/request.js:688:14)
          at Request.transition (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/request.js:22:10)
          at AcceptorStateMachine.runTo (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/state_machine.js:14:12)
          at /home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/state_machine.js:26:10
          at Request.<anonymous> (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/request.js:38:9)
          at Request.<anonymous> (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/request.js:690:12)
          at Request.callListeners (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
          at callNextListener (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
          at IncomingMessage.onEnd (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/event_listeners.js:336:13)
          at IncomingMessage.emit (events.js:412:35)
          at IncomingMessage.emit (domain.js:470:12)

eachRecursive:
  startAfter:      "accounts/0032c61e-38b1-4604-ba0b-51573bd1cfc7/assets/TIClgplRiuIjisdolSw7_Computer Whisperer.jpg"
  stopAt:          :accounts/O
  usePrefixBisect: false
  error:           Error:
    class: class Error
    stack:
      NoSuchKey: The specified key does not exist.
          at Request.extractError (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/services/s3.js:714:35)
          at Request.callListeners (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
          at Request.emit (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
          at Request.emit (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/request.js:688:14)
          at Request.transition (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/request.js:22:10)
          at AcceptorStateMachine.runTo (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/state_machine.js:14:12)
          at /home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/state_machine.js:26:10
          at Request.<anonymous> (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/request.js:38:9)
          at Request.<anonymous> (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/request.js:690:12)
          at Request.callListeners (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
          at Request.emit (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
          at Request.emit (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/request.js:688:14)
          at Request.transition (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/request.js:22:10)
          at AcceptorStateMachine.runTo (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/state_machine.js:14:12)
          at /home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/state_machine.js:26:10
          at Request.<anonymous> (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/request.js:38:9)
          at Request.<anonymous> (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/request.js:690:12)
          at Request.callListeners (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
          at callNextListener (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
          at IncomingMessage.onEnd (/home/ec2-user/.npm/_npx/24656/lib/node_modules/s3p/node_modules/aws-sdk/lib/event_listeners.js:336:13)
          at IncomingMessage.emit (events.js:412:35)
          at IncomingMessage.emit (domain.js:470:12)
```

**Comment by ivmakk** [comment]
It happens when the object's key includes some special chars like a space, square brackets (`]`, `[`), percentage (`%`), etc.   For example:
```sh
# will fail similar to s3p
$ aws s3 cp s3://bucket-name/some/srange/key name.txt s3://another-bucket-name/some/srange/key name.txt 
# will work
$ aws s3 cp "s3://bucket-name/some/srange/key name.txt" "s3://another-bucket-name/some/srange/key name.txt"
```

As a rough workaround, `s3p` prints in the end of execution all failed keys and in case of their "small" number of fails you may re-run operation for them by using native `aws s3` CLI.

**Comment by jclavoie-jive** [comment]
We get failures on "NoSuchKey" with the "+" sign too, which should be accepted by the doc. I assume the + might be wrongly encoded when the query is pushed and ends up as a space.

**Comment by klimchuk** [comment]
> We get failures on "NoSuchKey" with the "+" sign too, which should be accepted by the doc. I assume the + might be wrongly encoded when the query is pushed and ends up as a space.

I have the same problem, is it going to be fixed?

**Comment by klimchuk** [comment]
I found a way to fix issue with special characters by changing https://github.com/generalui/s3p/blob/master/source/S3Parallel/Lib/S3.caf from
`else
      copyOptions = merge
        if toFolder
          Bucket:     fromBucket
          Key:        fromKey

        else
          CopySource: "" #{fromBucket}/#{fromKey}
          Bucket:     toBucket
          Key:        toKey`

to

`else
      encodedFrom = "" #{fromBucket}/#{fromKey}
      copyOptions = merge
        if toFolder
          Bucket:     fromBucket
          Key:        fromKey

        else
          CopySource: encodeURIComponent encodedFrom
          Bucket:     toBucket
          Key:        toKey`

The rest is usual
sudo npm run build
sudo npm install /Users/user/Documents/Java/s3p -g

**Comment by shanebdavis** [comment]
This should be fixed with 3.4.6.
