### ISSUE TITLE
`s3p ls ... --pattern` results in error

### ISSUE THREAD

**Issue by btiernay** [generalui/s3p#67]
Issuing:
```
> s3p ls --bucket my-bucket --quiet --pattern 'json'                
```
Results in 
``` 
options:
  quiet:   true
  bucket:  my-bucket
  pattern: json
  fromCli: true
  mapList:
    (l) => {let from, into, to, i; from = l; into = from; if (from != null) {to = from.length; i = 0; while (i < to) {let item; item = from[i]; onItem(item); i++;};}; into; return null;}

Error:
  class: class Error
  stack:
    Error: only use one: with, map, pattern or mapList
        at Function.normalizeOptions (/Users/btiernay/.nvm/versions/node/v16.14.0/lib/node_modules/s3p/build/S3Parallel/S3Comprehensions.js:3:3100)
        at Function.each (/Users/btiernay/.nvm/versions/node/v16.14.0/lib/node_modules/s3p/build/S3Parallel/S3Comprehensions.js:3:7535)
        at Object.ls (/Users/btiernay/.nvm/versions/node/v16.14.0/lib/node_modules/s3p/build/S3Parallel/S3PCliCommands.js:3:1122)
        at run (/Users/btiernay/.nvm/versions/node/v16.14.0/lib/node_modules/s3p/build/S3Parallel/S3PCli.js:3:13416)
        at /Users/btiernay/.nvm/versions/node/v16.14.0/lib/node_modules/s3p/node_modules/@art-suite/cli/build/ArtSuite.Cli/Main.js:3:1036
        at r (/Users/btiernay/.nvm/versions/node/v16.14.0/lib/node_modules/s3p/node_modules/bluebird/js/browser/bluebird.core.min.js:31:18764)
        at Function.e.attempt.e.try (/Users/btiernay/.nvm/versions/node/v16.14.0/lib/node_modules/s3p/node_modules/bluebird/js/browser/bluebird.core.min.js:30:28875)
        at Function.start (/Users/btiernay/.nvm/versions/node/v16.14.0/lib/node_modules/s3p/node_modules/@art-suite/cli/build/ArtSuite.Cli/Main.js:3:818)
        at Object.main (/Users/btiernay/.nvm/versions/node/v16.14.0/lib/node_modules/s3p/build/S3Parallel/S3PCli.js:3:12588)
        at Object.<anonymous> (/Users/btiernay/.nvm/versions/node/v16.14.0/lib/node_modules/s3p/bin/s3p:2:28)
        at Module._compile (node:internal/modules/cjs/loader:1103:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
        at Module.load (node:internal/modules/cjs/loader:981:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
        at node:internal/main/run_main_module:17:47
```

**Comment by shanebdavis** [comment]
fixed in 3.4.3
