### ISSUE TITLE
RequestTimeTooSkewed: The difference between the request time and the current time is too large

### ISSUE THREAD

**Issue by trav-c** [generalui/s3p#80]
During a long running s3p sync operation (copying data between S3 buckets in two different regions), I encountered a flood of the following error messages

```
Error:
  class: class Error
  stack:
    RequestTimeTooSkewed: The difference between the request time and the current time is too large.
        at Request.extractError (/usr/lib/node_modules/s3p/node_modules/aws-sdk/lib/services/s3.js:711:35)
        at Request.callListeners (/usr/lib/node_modules/s3p/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
        at Request.emit (/usr/lib/node_modules/s3p/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
        at Request.emit (/usr/lib/node_modules/s3p/node_modules/aws-sdk/lib/request.js:686:14)
        at Request.transition (/usr/lib/node_modules/s3p/node_modules/aws-sdk/lib/request.js:22:10)
        at AcceptorStateMachine.runTo (/usr/lib/node_modules/s3p/node_modules/aws-sdk/lib/state_machine.js:14:12)
        at /usr/lib/node_modules/s3p/node_modules/aws-sdk/lib/state_machine.js:26:10
        at Request.<anonymous> (/usr/lib/node_modules/s3p/node_modules/aws-sdk/lib/request.js:38:9)
        at Request.<anonymous> (/usr/lib/node_modules/s3p/node_modules/aws-sdk/lib/request.js:688:12)
        at Request.callListeners (/usr/lib/node_modules/s3p/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
        at Request.emit (/usr/lib/node_modules/s3p/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
        at Request.emit (/usr/lib/node_modules/s3p/node_modules/aws-sdk/lib/request.js:686:14)
        at Request.transition (/usr/lib/node_modules/s3p/node_modules/aws-sdk/lib/request.js:22:10)
        at AcceptorStateMachine.runTo (/usr/lib/node_modules/s3p/node_modules/aws-sdk/lib/state_machine.js:14:12)
        at /usr/lib/node_modules/s3p/node_modules/aws-sdk/lib/state_machine.js:26:10
        at Request.<anonymous> (/usr/lib/node_modules/s3p/node_modules/aws-sdk/lib/request.js:38:9)
        at Request.<anonymous> (/usr/lib/node_modules/s3p/node_modules/aws-sdk/lib/request.js:688:12)
        at Request.callListeners (/usr/lib/node_modules/s3p/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
        at callNextListener (/usr/lib/node_modules/s3p/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
        at IncomingMessage.onEnd (/usr/lib/node_modules/s3p/node_modules/aws-sdk/lib/event_listeners.js:417:13)
        at IncomingMessage.emit (events.js:412:35)
        at IncomingMessage.emit (domain.js:475:12)
```

While I know this error can occur due to clock sync problems on the system running s3p, I'm quite confident that was not the case here - the sync was running an an EC2 instance (z1d.6xlarge) and the instance is synced to NTP (using the native AWS ntp server):
```
# chronyc tracking
Reference ID    : A9FEA97B (169.254.169.123)
Stratum         : 4
Ref time (UTC)  : Thu Feb 09 23:18:29 2023
System time     : 0.000011213 seconds slow of NTP time
Last offset     : -0.000024331 seconds
RMS offset      : 0.000047053 seconds
Frequency       : 3.999 ppm slow
Residual freq   : -0.254 ppm
Skew            : 1.425 ppm
Root delay      : 0.000303258 seconds
Root dispersion : 0.000302206 seconds
Update interval : 16.2 seconds
Leap status     : Normal
```

Based on some research I suspect the issue is that internally some requests spent too long queued before being executed, for example,[ this post](https://stackoverflow.com/questions/4770635/s3-error-the-difference-between-the-request-time-and-the-current-time-is-too-la) states:

> This can also be caused by using async/await with the construction of the request object outside the task and the actual call to AWS inside the task. If there are lots of tasks running and the task isn't scheduled in time, or there is some other operation delaying the actual call to AWS, this exception may be thrown. This is more common than you might guess because the default task scheduler does not process tasks in FIFO order, resulting in starvation for some tasks, especially under heavy load.

One possible workaround, might be to use the [correctClockSkew](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#correctClockSkew-property) setting the SDK, but I suspect that actually won't work here, as I don't believe there is actually client clock skew (the option appears to just retry requests with a calculated clock skew based on the API's HTTP `Date` response header

**Comment by shanebdavis** [comment]
Very interesting. I'm not sure. The creation of the request object happens immediately before the request is sent. Does this error appear immediately when you start the run, or does it only happen after s3p has been running for a while?

**Comment by trav-c** [comment]
If I recall correctly it was not happening until some time into the run, however for a variety of reasons we are no longer using s3p and have moved our mass copy operations over to a mix of S3 native replication and AWS DataSync, so I don't really have the setup to confirm that anymore.

**Comment by shanebdavis** [comment]
Got it. Thanks for cycling back.
